/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FcIcon {
        "color": string;
        "name": string;
        "size": number;
    }
}
declare global {
    interface HTMLFcIconElement extends Components.FcIcon, HTMLStencilElement {
    }
    var HTMLFcIconElement: {
        prototype: HTMLFcIconElement;
        new (): HTMLFcIconElement;
    };
    interface HTMLElementTagNameMap {
        "fc-icon": HTMLFcIconElement;
    }
}
declare namespace LocalJSX {
    interface FcIcon {
        "color"?: string;
        "name"?: string;
        "size"?: number;
    }
    interface IntrinsicElements {
        "fc-icon": FcIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fc-icon": LocalJSX.FcIcon & JSXBase.HTMLAttributes<HTMLFcIconElement>;
        }
    }
}
